//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunYonetimi_EntityFrameworkDatabaseFirst_
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoriTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KategoriTb()
        {
            this.UrunlerTb = new HashSet<UrunlerTb>();
        }
    
        public int ID { get; set; }
        public string KategoriAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunlerTb> UrunlerTb { get; set; }
    }
}
