//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunYonetimi_EntityFrameworkDatabaseFirst_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrunYonetimiDBEntities : DbContext
    {
        public UrunYonetimiDBEntities()
            : base("name=UrunYonetimiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KategoriTb> KategoriTb { get; set; }
        public virtual DbSet<MusterilerTb> MusterilerTb { get; set; }
        public virtual DbSet<SatislarTb> SatislarTb { get; set; }
        public virtual DbSet<UrunlerTb> UrunlerTb { get; set; }
    }
}
