//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunYonetimi_EntityFrameworkDatabaseFirst_
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatislarTb
    {
        public int SatısID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual MusterilerTb MusterilerTb { get; set; }
        public virtual UrunlerTb UrunlerTb { get; set; }
    }
}
