// <auto-generated />
namespace MyFarmYS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class kurulum20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kurulum20));
        
        string IMigrationMetadata.Id
        {
            get { return "202108111554260_kurulum2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
